name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: ./cache
        # An explicit key for restoring and saving the cache
        key: jut44d6nv9
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Decode google-services.json file
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      run: echo $GOOGLE_SERVICES > ./app/google-services.json
    - name: Build with Gradle
      run: ./gradlew build
